### ISSUE TITLE
`AttributeError: 'list' object has no attribute 'lower'`

### ISSUE THREAD

**Issue by arokem** [MaxHalford/Flask-Boilerplate#1]
<img width="1434" alt="screen shot 2015-11-23 at 3 31 19 pm" src="https://cloud.githubusercontent.com/assets/118582/11353365/48a0d3b4-91f7-11e5-956a-3c74ca90b47f.png">

This happens on both python 2 and python 3, running on a mac laptop.

**Comment by MaxHalford** [comment]
I think I pushed a wrong config.py file. What happens if you replace `SERVER_NAME = ['localhost:5000']` with `SERVER_NAME = 'localhost:5000'` in `config.py`?

**Comment by MaxHalford** [comment]
Okay for some reason this didn't bug out for me, however the syntax was wrong. It's fixed now.
