### ISSUE TITLE
Error when running "python manage.py initdb"

### ISSUE THREAD

**Issue by cukal** [MaxHalford/Flask-Boilerplate#9]
Error when running `python manage.py initdb` 

>  (most recent call last):
  File "manage.py", line 4, in <module>
    from app import app, db, models
  File "/home/dileoz/temp/flask-boilerplate/app/__init__.py", line 9, in <module>
    from app.logger_setup import logger
  File "/home/dileoz/temp/flask-boilerplate/app/logger_setup.py", line 65
    file_handler.setLevel(logging.DEBUG)
    ^
IndentationError: unexpected indent

Reverting to 183c8871a23fb29d29f1df2d726ce9cfe625f968 and executing `python manage.py initdb` works.

**Comment by MaxHalford** [comment]
Fixed via [this PR](https://github.com/MaxHalford/flask-boilerplate/pull/8).
